import type { ComponentType, SVGProps } from "react";
import {
  AddRegular,
  AlertRegular,
  AppsListRegular,
  ArchiveRegular,
  ArrowCircleUpRegular,
  ArrowCounterclockwiseRegular,
  ArrowDownloadRegular,
  ArrowDownRegular,
  ArrowExportRegular,
  ArrowLeftRegular,
  ArrowMaximizeRegular,
  ArrowMinimizeRegular,
  ArrowRightRegular,
  ArrowSyncRegular,
  ArrowUpRegular,
  ArrowUploadRegular,
  Battery10Regular,
  BatteryChargeRegular,
  BookOpenRegular,
  BoxRegular,
  CameraRegular,
  ChatRegular,
  CheckmarkCircleRegular,
  CheckmarkRegular,
  ChevronDownRegular,
  ChevronLeftRegular,
  ChevronRightRegular,
  ChevronUpRegular,
  CircleFilled,
  ClipboardPasteRegular,
  ClockRegular,
  CloudRegular,
  CodeRegular,
  CopyRegular,
  DataBarVerticalRegular,
  DeleteRegular,
  DesktopSpeakerRegular,
  DismissRegular,
  DatabaseRegular,
  DocumentRegular,
  DocumentSettingsRegular,
  DocumentTextRegular,
  DropRegular,
  ErrorCircleRegular,
  EyeOffRegular,
  EyeRegular,
  FolderRegular,
  GamesRegular,
  GaugeRegular,
  GlobeRegular,
  GridDotsRegular,
  HardDriveRegular,
  HomeRegular,
  ImageRegular,
  InfoRegular,
  LinkRegular,
  LockClosedKeyRegular,
  LockClosedRegular,
  MailRegular,
  MoviesAndTvRegular,
  MoreHorizontalRegular,
  MusicNote2Regular,
  NewsRegular,
  OpenFolderRegular,
  PanelLeftRegular,
  PauseRegular,
  PeopleRegular,
  PersonCircleRegular,
  PlayRegular,
  PlugConnectedRegular,
  PlugConnectedSettingsRegular,
  PowerRegular,
  PulseRegular,
  PulseSquareRegular,
  RamRegular,
  ReOrderDotsVerticalRegular,
  SaveRegular,
  SearchRegular,
  ServerRegular,
  SettingsRegular,
  ShieldRegular,
  ShoppingBagRegular,
  SignOutRegular,
  SparkleRegular,
  SpinnerIosRegular,
  StarFilled,
  StopRegular,
  SubtractRegular,
  TemperatureRegular,
  TextSortAscendingRegular,
  TextSortDescendingRegular,
  ToggleLeftRegular,
  ToggleRightRegular,
  VideoRegular,
  WarningRegular,
  WarningShieldRegular,
  WeatherDrizzleRegular,
  WeatherFogRegular,
  WeatherPartlyCloudyDayRegular,
  WeatherRainRegular,
  WeatherSnowRegular,
  WeatherSunnyRegular,
  WeatherThunderstormRegular,
  Wifi1Regular,
  Wifi3Regular,
  Wifi4Regular,
  WifiOffRegular,
  WindowConsoleRegular,
  WrenchRegular,
  CutRegular,
} from "@fluentui/react-icons";

export type LucideIcon = ComponentType<SVGProps<SVGSVGElement>>;

export {
  PulseSquareRegular as Activity,
  ErrorCircleRegular as AlertCircle,
  WarningRegular as AlertTriangle,
  ArrowDownRegular as ArrowDown,
  ArrowLeftRegular as ArrowLeft,
  ArrowRightRegular as ArrowRight,
  ArrowUpRegular as ArrowUp,
  ArrowCircleUpRegular as ArrowUpCircle,
  DataBarVerticalRegular as BarChart3,
  BatteryChargeRegular as BatteryCharging,
  Battery10Regular as BatteryFull,
  AlertRegular as Bell,
  BookOpenRegular as BookOpen,
  CameraRegular as Camera,
  CheckmarkRegular as Check,
  CheckmarkRegular as CheckIcon,
  CheckmarkCircleRegular as CheckCircle2,
  ChevronDownRegular as ChevronDownIcon,
  ChevronLeftRegular as ChevronLeftIcon,
  ChevronRightRegular as ChevronRight,
  ChevronRightRegular as ChevronRightIcon,
  ChevronUpRegular as ChevronUpIcon,
  CircleFilled as CircleIcon,
  ClipboardPasteRegular as ClipboardPaste,
  ClockRegular as Clock,
  CloudRegular as Cloud,
  WeatherDrizzleRegular as CloudDrizzle,
  WeatherFogRegular as CloudFog,
  WeatherThunderstormRegular as CloudLightning,
  WeatherRainRegular as CloudRain,
  WeatherSnowRegular as CloudSnow,
  WeatherPartlyCloudyDayRegular as CloudSun,
  CodeRegular as Code,
  BoxRegular as Container,
  CopyRegular as Copy,
  PulseRegular as Cpu,
  DatabaseRegular as Database,
  ArrowDownloadRegular as Download,
  EyeRegular as Eye,
  EyeOffRegular as EyeOff,
  DocumentRegular as File,
  ArchiveRegular as FileArchive,
  CodeRegular as FileCode,
  DocumentSettingsRegular as FileCog,
  ImageRegular as FileImage,
  DocumentTextRegular as FileText,
  VideoRegular as FileVideo,
  MoviesAndTvRegular as Film,
  FolderRegular as Folder,
  OpenFolderRegular as FolderOpen,
  GamesRegular as Gamepad2,
  GaugeRegular as Gauge,
  GlobeRegular as Globe,
  ReOrderDotsVerticalRegular as GripVerticalIcon,
  HardDriveRegular as HardDrive,
  HomeRegular as Home,
  InfoRegular as Info,
  GridDotsRegular as LayoutGrid,
  LinkRegular as Link2,
  AppsListRegular as List,
  SpinnerIosRegular as Loader2,
  SpinnerIosRegular as Loader2Icon,
  LockClosedRegular as Lock,
  LockClosedKeyRegular as LockKeyhole,
  SignOutRegular as LogOut,
  MailRegular as Mail,
  ArrowMaximizeRegular as Maximize2,
  RamRegular as MemoryStick,
  ChatRegular as MessageSquare,
  ArrowMinimizeRegular as Minimize2,
  SubtractRegular as Minus,
  SubtractRegular as MinusIcon,
  DesktopSpeakerRegular as MonitorSpeaker,
  MoreHorizontalRegular as MoreHorizontal,
  MoreHorizontalRegular as MoreHorizontalIcon,
  MusicNote2Regular as Music,
  GlobeRegular as Network,
  BoxRegular as Package,
  PauseRegular as Pause,
  PlayRegular as Play,
  PlugConnectedRegular as Plug,
  PlugConnectedSettingsRegular as PlugZap,
  AddRegular as Plus,
  PanelLeftRegular as PanelLeftIcon,
  PowerRegular as Power,
  ArrowSyncRegular as RefreshCw,
  ArrowCounterclockwiseRegular as RotateCcw,
  NewsRegular as Rss,
  WrenchRegular as Wrench,
  SearchRegular as Search,
  SearchRegular as SearchIcon,
  ServerRegular as Server,
  SettingsRegular as Settings,
  SettingsRegular as Settings2,
  ShieldRegular as Shield,
  WarningShieldRegular as ShieldAlert,
  ShoppingBagRegular as ShoppingBag,
  TextSortAscendingRegular as SortAsc,
  TextSortDescendingRegular as SortDesc,
  SparkleRegular as Sparkles,
  StopRegular as Square,
  StarFilled as Star,
  DocumentTextRegular as ScrollText,
  Wifi4Regular as SignalHigh,
  Wifi1Regular as SignalLow,
  Wifi3Regular as SignalMedium,
  WeatherSunnyRegular as Sun,
  WindowConsoleRegular as TerminalSquare,
  TemperatureRegular as Thermometer,
  ToggleLeftRegular as ToggleLeft,
  ToggleRightRegular as ToggleRight,
  DeleteRegular as Trash2,
  ArrowUploadRegular as Upload,
  PersonCircleRegular as UserRound,
  PeopleRegular as Users,
  Wifi4Regular as Wifi,
  WifiOffRegular as WifiOff,
  ArrowUpRegular as Wind,
  SaveRegular as Save,
  ArrowExportRegular as ExternalLink,
  DropRegular as Droplets,
  CutRegular as Scissors,
  DismissRegular as XIcon,
  DismissRegular as X,
};
