sonar.projectKey=doctor-io_home-server
sonar.organization=doctor-io

sonar.sources=.
sonar.exclusions=node_modules/**,.next/**,dist-server/**,coverage/**,drizzle/**,packages/**,**/*.test.ts,**/*.test.tsx,test/**

sonar.tests=.
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
